### ISSUE TITLE
RPM releases

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#154]
### What needs to be done
We target K8s primarily, but do we want to look into making RPM releases? OBS's SCM integration with Github is considered sufficiently stable now that we could: https://openbuildservice.org/2022/09/21/trigger-workflow-rollout/

### Why it needs to be done

It would be a differentiation from MinIO since you don't need a container runtime to expose storage via S3 (at least on SLE/openSUSE).

### Additional Information

This suggestion comes from a conversation between @jhmarina & @m-ildefons

**Comment by tserong** [comment]
I accidentally did some experimental work on this today, because I already had our ceph fork kinda building in https://build.opensuse.org/project/show/filesystems:ceph:s3gw as part of the work on #162...

What I've done is taken the existing ceph.spec file, switch to using ninja instead of make, ripped out all the ceph-* subpackages, added a new s3gw subpackage, and fixed up the %install section so it only installs the radosgw binary and required libraries (see https://build.opensuse.org/package/view_file/filesystems:ceph:s3gw/ceph/ceph.spec?expand=1 and look for all the "tserong" comments) . This does give a functional s3gw RPM. If you're logged in to OBS, you can download it from https://build.opensuse.org/package/binaries/filesystems:ceph:s3gw/ceph/15.4. I deliberately disabled publishing for that package in case someone actually tried to use it ;-)

I did the above because I found it easiest to tweak ceph.spec incrementally to get something that worked. What I think we should _really_ do, instead of messing around with subpackages in ceph.spec, is create a separate s3gw.spec file, based on the existing ceph.spec, which just has the one s3gw package, i.e. the main package definition would start with `Name: s3gw` instead of the existing `Name: ceph`, and there would be no subpackages at all. That spec file could either live perpetually in our downstream ceph fork, or maybe it could go in the s3gw repo. Not sure. Anyway, once we've got that we should be able to automate package builds on OBS, and once that's done, we could conceivably even do container builds on OBS too.

**Comment by tserong** [comment]
One other thing we should do for an RPM is add a systemd unit file and probably /etc/sysconfig/s3gw which can set things like the data directory. That's not necessary for use inside our container which would presumably continue to run via ENTRYPOINT, but would be useful for anyone using the RPM by itself on random Linux systems.

**Comment by tserong** [comment]
I now have an s3gw package in https://build.opensuse.org/package/show/filesystems:ceph:s3gw/s3gw built from the v0.7.0 sources. The spec file is manually derived from ceph.spec. I've also experimentally added a systemd unit file and /etc/sysconfig/ceph with some config options, just to see what it's like using s3gw as a _package_, not as a container. When used that way, I've set it to use /var/lib/s3gw for the data path, and added an unprivileged s3gw user for the daemon to run as. These extra things are not necessary for containerized use.

On the container front, I've created https://build.opensuse.org/package/show/filesystems:ceph:s3gw/s3gw-image, which builds a container image on OBS, using the s3gw RPM. This container sets the data path to /data, same as the containers we usually work with.

Neither of the above (the s3gw RPM nor the s3gw container) have actually been published by the build service yet :-/ but I have built and tested them locally.

The spec file and other bits and pieces so far only exist in OBS. I haven't yet figured out where the should live in our source tree.

I also still need to look at the OBS SCM integration.

**Comment by tserong** [comment]
...and now everything is published. So, if you want to play with an s3gw RPM build for Leap 15.4, that's now in https://download.opensuse.org/repositories/filesystems:/ceph:/s3gw/15.4/

You can get the container with `podman pull registry.opensuse.org/filesystems/ceph/s3gw/containers/s3gw/s3gw:latest`.
