### ISSUE TITLE
[FR] Add support for default nginx ingress in helm chart

### ISSUE THREAD

**Issue by Martin-Weiss** [s3gw-tech/s3gw#235]
At the moment the helm chart requires traefic to be available as ingress solution.
Within default RKE2 clusters we have nginx ingress and the helm chart should allow to use that.

**Comment by enzo-dechaene** [comment]
Has anyone installed it and tried it with a custom nginx ingress ?
I have a 404 with a CORS problem, I feel like I must have forgotten some annotations in the ingress

**Comment by enzo-dechaene** [comment]
I figure it out when I added the cors annotations to nginx, but now I get the following error 
`{"Code":"SignatureDoesNotMatch","HostId":""}`

**Comment by giubacc** [comment]
@enzo-dechaene I suspect the error you got is because nginx is not passing all the headers to the s3gw backend.
`host` header is especially important when the backend computes the HMAC signature.
We are currently in a phase where we are designing a new architecture for the frontend and we count on starting a revision for the ingresses after that.

**Comment by giubacc** [comment]
I'm closing this as it is a duplicate of https://github.com/aquarist-labs/s3gw/issues/389.
