### ISSUE TITLE
rgw/sfs: Investigate if radosgw can handle CORS

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#275]
### What needs to be done

Investigate if we can handle CORS at radosgw level instead of using Traefik.

### Why it needs to be done

While investigating how to leverage Rancher's ingress instead of using Traefik in Rancher Manager, we've found out that one of the issues we need to sort out is how we handle CORS.

### Acceptance Criteria

The outcome should be either a confirmation that radosgw is able to handle CORS or an alternative proposal. The ultimate goal is to offer the user the possibility of choosing the desired ingress. We will then define the next steps.

### Additional Information

If `radosgw` can handle CORS, this is the issue for the implementation: https://github.com/aquarist-labs/s3gw/issues/388

**Comment by jecluis** [comment]
Because I was trying to test the UI this weekend and bumping into CORS issues[^1], I decided to dedicate some time looking into CORS so I could be entertained. I found that the answer to this issue is both "yes" and "no".

RGW supports CORS on buckets, but doesn't have a way to specify CORS policies for the RGW itself. This means that while RGW will reply with the appropriate CORS fields if the bucket has a CORS configuration and rules[^2], if the bucket has no CORS policy or we are issuing an operation that is not on a bucket, there will be no CORS fields being populated in the response headers.

I hacked away at forcing CORS headers to be populated, and it sort of works[^3], but in the process I realized something: **We can't have the UI talking directly to RGW and relying on CORS**.

Even if we have RGW replying by default with an `Access-Control-Allow-Origin: *` on all requests that are not targeting a bucket with a CORS policy, it only takes the user to set a CORS policy other than `Access-Control-Allow-Origin: *` on a bucket for the UI to break. And we can't have the ingress rewriting the CORS headers for RGW to make the UI work because that will likely be overriding the bucket-specific CORS policies.

The only way out of this that I see is having a backend for the UI. It could either be a full functioning RGW client (S3 and admin ops), or it could be nothing but a shim layer to direct requests to and from RGW. That way we don't need to be doing black magic with ingresses, nor are we subject to CORS issues in general.


[^1]: It is possible to configure the UI to use the proxy URL when running `ng serve`, but this seemed hackish to me, and thus deserving of investigation.
[^2]: Was not tested, but the code is there. And being based in bucket attributes, I don't see a reason for it not to work with SFS.
[^3]: Although not very well, more thought would have to go into such an implementation to cover all cases properly, and I was still not providing the CORS information as the browser expects it to be.

**Comment by jhmarina** [comment]
The team discussed the issue in the planning call and the outcome is that we will implement a backend for the UI, which will sort out the CORS issues. More information: https://confluence.suse.com/display/RES/2023-03-13+-+s3gw+planning+call
