### ISSUE TITLE
[BUG]exec /radosgw/radosgw: exec format error

### ISSUE THREAD

**Issue by ulzii0819** [s3gw-tech/s3gw#305]
Hi, 

After deployed s3gw on k3s cluster pod is crashing continuously. Also it gave me the below error message. 

![image](https://user-images.githubusercontent.com/121950474/211488558-5cf1279f-38c4-474e-8a21-51b4d033233c.png)

My environment includes : 
k3s cluster with deployed on Oracle Linux 9, version v1.25.4+k3s1
longhorn 1.4.0
s3gw 0.10.0

Please help me.

**Comment by l-mb** [comment]
Just adding information from the community Slack: this is AMD EPYC 7443P, kernel version : 5.15.0-5.76.5.1.el9uek.x86_64, so not an aarch64 vs x86_64 incompatibility.

I suspect we're generating the binary with some features that the Oracle Linux platform doesn't enable somehow. We should add Oracle's Enterprise Linux to the CI/CD system to prevent those in the future if we can.

**Comment by jecluis** [comment]
@ulzii0819 how reproducible is this? if you happen to do a new k3s installation, does this happen every time? Turns out @irq0 found an on-going bug in containerd (https://github.com/containerd/containerd/issues/5854) that might be relevant here. One of the workarounds is to remove the (potentially corrupted) image from the internal registry (https://github.com/containerd/containerd/issues/5854#issuecomment-1258115142). Would you mind trying that out?

**Comment by ulzii0819** [comment]
@jecluis , it happens every time when I do a new k3s installation on Oracle Linux v9 with CPU:AMD EPYC 7443P. Maybe you can reproduce the case by installing K3S over Oracle Linux 9 machine and deploy s3gw on it.

**Comment by m-ildefons** [comment]
Hi @ulzii0819 ,
thanks for the bug report. I was able to reproduce the issue under QEMU. The problem seems to be that the binary is missing the `.note.ABI-tag` ELF section. This section is [specified in the LSB](https://refspecs.linuxfoundation.org/LSB_1.2.0/gLSB/noteabitag.html) and apparently Oracle Linux enforces this more strictly than other systems.

I was able to create a container image with the tag present in the binary and successfully run it in the same VM that previously failed to run the release container with the same error as you described. There is a fix in flight now and I expect the next version to be compatible with Oracle Linux 9.
