### ISSUE TITLE
rgw/sfs: make garbage collector smarter

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#358]
In certain scenarios, it would be desirable that upon an object deletion, the system also sync deletes the related files on the volume.
This would allow the user to immediately re-use the freed space on the volume. 
This mode could be defined `per-bucket` in the bucket metadata and/or enabled globally with a parameter.
The first option requires to define a non-standard call that would allow a client to configure a bucket.
The second option is more easy but it would define a global behavior.

**Comment by l-mb** [comment]
This should happen automatically and not need to be configured per-bucket.

e.g., keeping track of the space occupied by marked-for-deletion objects is a simple counter, and when someone tries to `PUT` an object that we could otherwise not store, a garbage collector run should happen automatically. (Or when the allocatable space gets too low, or periodically as a background task.)

The system should also always immediately report the logically free space, not the one pre-GC.

So I don't think a "hard deletion" feature is the best way to address the issue.

Does that make sense?

**Comment by giubacc** [comment]
It makes sense.
Probably we need to extend this [issue](https://github.com/aquarist-labs/s3gw/issues/357) to catch all the behaviors we want to support, but in terms of Garbage Collection.
The strong need here is that if there is a physical space that could be used because logically deleted, then an operation that could not fail, should not fail.
What is not acceptable from the point of view of this issue's need, is that an operation fails because an asynch event still has not occurred.

**Comment by irq0** [comment]
Context:

We return ERR_QUOTA_EXCEEDED when
1. Filesystem reservation hit. (https://github.com/aquarist-labs/ceph/pull/74). Quite simplistic at the moment. We check that there is at least $min space left before attempting a write op. Space left is updated every $interval (defaults 100M, 10 seconds).
3. (in flight) https://github.com/aquarist-labs/ceph/pull/119 we get ENOSPC on an IO operation

**Comment by irq0** [comment]
We could trigger GC when reservation hit (1.) and when we get an ENOSPC from storage (2. when landed)

Until (2.) ENOSPC that sneaks past (1.) will probably trigger an exception and bubble up to our exception-to-500 handler.

Some nuance on whether we keep the client waiting for GC or replying with ERR_QUOTA_EXCEEDED immediately and trust on the client's retry logic will come back (hopefully) when we are done with GC.

**Comment by giubacc** [comment]
What we should avoid is this:

1. 
```
$ epinio app push -n myniceapplication
ERROR: disk full
```
ok, no problem, the user deletes some apps he doesn't use anymore:

2. 
```
$ epinio app delete -n myfatapplication
OK
```
now the user legitimately thinks there is space, but:

3. 
```
$ epinio app push -n myniceapplication
ERROR: disk full
```
4. the user now picks up the phone and yells at the Epinio's service support :grin:

**Comment by irq0** [comment]
Epinio uses github.com/minio/minio-go/v7 v7.0.47. Retry logic is in https://github.com/minio/minio-go/blob/master/retry.go

Summary: Does not retry ERR_QUOTA_EXCEEDED which is  HTTP 403 with payload "QuotaExceeded"

**Comment by giubacc** [comment]
I'm not entirely sure that this issue is completely solvable with a retry strategy.
What if the retry is configured to retry only 2 times and this is not sufficient?
IMO the solution should be demanded to the server not to the client.

**Comment by irq0** [comment]
The retry comment is related to the "trigger GC on no/low space condition" approach.
Should we go that route, instead of immediate deletes, we need to design around retries, timeouts and errors.

Example: PUT hits no space, we start GC. We don't know if and when GC makes enough room. Other writes, for instance, may happen at the same time. unlink() may be slow because disk is saturated.

What to do with the PUT request? We can't hang forever - there are client and server-side (65s) request timeouts (usually retryable). If we return early with QuotaExceeded we make clients unhappy as they don't retry this error.

We need to consider "PUT hits no space, but we GC" as a new condition. 
Either wait until request timeout, or return and let the client retry in a bit.

**Comment by jecluis** [comment]
> Example: PUT hits no space, we start GC. We don't know if and when GC makes enough room. Other writes, for instance, may happen at the same time. unlink() may be slow because disk is saturated.
> 
> 
> 
> What to do with the PUT request? We can't hang forever - there are client and server-side (65s) request timeouts (usually retryable). If we return early with QuotaExceeded we make clients unhappy as they don't retry this error.

The garbage collector becoming smarter may address this. Instead of triggering only when we are at the line, we may instead choose to trigger when we are over a given (yet another) threshold. Given we're checking how close to full we are every N seconds, we might as well have that thread trigger the GC process if we get too close to the line for comfort.

And we might want to make GC smarter as well in the way we remove objects from disk. We can choose to delete larger objects first, for instance. That should give us a greater bang for the buck should the system be too saturated.

**Comment by jhmarina** [comment]
I'm closing this issue for now since we had a call and defined the next steps for GC. Here is the issue: https://github.com/aquarist-labs/s3gw/issues/393
