### ISSUE TITLE
COSI driver investigation

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#433]
Investigate whether Ceph's COSI driver implementation can be leveraged to integrate with Longhorn.

**Comment by giubacc** [comment]
COSI architecture is composed by 3 actors:

1. COSI controller, 1 per cluster, it validates all the CRDs issued by users for all the S3 providers in the cluster.
2. COSI sidecar, 1 per S3 provider; it is an S3 provider agnostic component that is reading COSI CRDs and translate them into gRPC calls to the COSI driver.
3. COSI driver, 1 per S3 provider, it is the component acting as server of the sidecar and as client vs the S3 provider.

The controller and sidecar are COSI standard components that are provided as is and don't require customizations.
The driver is the component that could require customization depending on the S3 provider.

The controller lives in an isolated pod in the default namespace, it is a cluster scoped component.
The sidecar and the driver are packed into 2 containers in the same pod (they communicate via gRPC).

For the s3gw project we started from the COSI driver implementation for Ceph RGW: https://github.com/ceph/ceph-cosi.
An initial testing version for s3gw has been derived from that and placed here: https://github.com/giubacc/s3gw-cosi-driver.

Topics:

1. Kubernetes version supported for s3gw: 1.24; 1.25+; starting from 1.25, K8s should be shipped out with a COSI implementation. Earlier versions require CRDs and the controller to be manually deployed. 
2. KEY, IAM authentications; for now we have tested KEY mechanism, IAM seems to be the preferred way because it grants implicitly the pod with the authorization to access the S3 service;  we have to investigate the status of IAM implementation for s3gw. 
3. We have to investigate COSI in a scenario where multiple instances of s3gw are deployed (namespaces, labels, etc).
4. (future) Investigate the possibility to automatically trigger an installation of s3gw in the cluster on demand supposing an user creates an instance of a claim for a BucketClass not yet bound to an s3gw service.
5. UI inconsistences (provisioned users not seeing provisioned buckets).
6. Deletion mechanisms associated to provisioned objects (what happens when a COSI CRD is deleted? and the associated objects?)

**Comment by giubacc** [comment]
- [controller upstream](https://github.com/kubernetes-sigs/container-object-storage-interface-controller)
- [sidecar upstream](https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar) 
- [driver downstream](https://github.com/aquarist-labs/s3gw-cosi-driver)
