### ISSUE TITLE
head_object/get_object/ more: Missing VersionId in response

### ISSUE THREAD

**Issue by irq0** [s3gw-tech/s3gw#526]
Many responses don't have the VersionID / x-amz-version-id set.

For head_object requests:

head object requests..
are RGWGetObj RGW operations with get_data == false..
create a ReadOp, call prepare, never call iterate()..
retrieve attrs by calling get_attrs on the SAL object
retrieve the version_id from object get_instance()

relevant op code:
```
  op_ret = read_op->prepare(s->yield, this);
  if (op_ret < 0)
    goto done_err;
  version_id = s->object->get_instance();
  s->obj_size = s->object->get_obj_size();
  attrs = s->object->get_attrs();
```

Theory: we don't set the instance in the object's cached state (RGWObjState)

S3 Tests failing because of this:

test_object_lock_delete_object_with_retention_and_marker	fail
test_object_lock_get_obj_metadata	fail
test_object_lock_uploading_obj	fail
test_versioned_object_acl_no_version_specified	fail
test_versioning_multi_object_delete_with_marker	fail
test_versioning_obj_plain_null_version_overwrite	fail

**Comment by 0xavi0** [comment]
I fixed this one today, working on the versioning stuff... PR coming in the next days.
Some of the tests in the list still fail, but not because of the missing `VersionId` in the response.
For example:

**S3TEST_CONF=s3tests.conf tox -- s3tests_boto3/functional/test_s3.py::test_object_lock_delete_object_with_retention_and_marker**
```python
        if http.status_code >= 300:
            error_code = parsed_response.get("Error", {}).get("Code")
            error_class = self.exceptions.from_code(error_code)
>           raise error_class(parsed_response, operation_name)
E           botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the DeleteObject operation: forbidden by object lock
```

When versioning work is done I'll re-tests those `s3 tests` and will open new issues for those still not passing.
