### ISSUE TITLE
Non disruptive upgrade w/o downtime (Epic)

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#544]
### What needs to be done
Ensure non-disruptive upgrades for s3gw:

Implement the ability to upgrade s3gw images seamlessly during the Longhorn upgrade process.
Aim for minimal-to-no downtime during the upgrade to avoid interruptions in s3gw functionality.

### Acceptance Criteria
These are still to be defined.

### Additional Information
https://confluence.suse.com/display/RES/Longhorn-s3gw+Integration+Plan#Longhorns3gwIntegrationPlan-%22Experimental%22Schedule

```[tasklist]
### My tasks
```

**Comment by jecluis** [comment]
@m-ildefons what do we need here? Does the preloading images on all nodes ( #734 ) somewhat address this?

**Comment by m-ildefons** [comment]
Preloading the images is not enough, but it would help minimize the downtime.

The Longhorn manager owns the deployments of s3gw, so when an update of an s3gw instance is triggered, it needs to update the deployment spec and ensure the containers are restarted. But this has to be done carefully to avoid dead-locking on the exclusive access to the volume.

A dead lock can happen during the process if the shut-down of the old instance is waiting for the new instance to be ready (which is default behavior in K8s). Since the new instance can not become ready as long as the old instance is alive, as it needs exclusive access to the volume, this situation may require explicitly shutting down the old instance.
It's best for this to carefully configure the deployment to behave this way, if possible rather than micro-manage K8s, but that requires testing that the selected configuration works as desired.

This issue exists mostly for me to keep track of what still needs to be done in the Longhorn controller, or at least needs to be confirmed that it works.

**Comment by jecluis** [comment]
Can we create those issues so we are aware of what they are? And add them as tasks to this issue?

**Comment by jecluis** [comment]
As agreed on yesterday's planning call, we'll be pushing this to post LH 1.6. @m-ildefons please add any additional information here that might be relevant.

**Comment by jecluis** [comment]
Being LH focused, we're no longer planning on working on this, in this specific context.
