### ISSUE TITLE
s3gw-charts 0.18 not fully usable as a subchart due to inherited resource names from a parent chart

### ISSUE THREAD

**Issue by thehejik** [s3gw-tech/s3gw#630]
ref. https://github.com/epinio/epinio/issues/2466
PR with related changes https://github.com/aquarist-labs/s3gw-charts/pull/98

In current `epinio v1.9.0-rc4` we have bumped s3gw subchart from 0.14 to 0.18 and suddenly some of the s3gw resources are having a different names inherited from parent epinio chart which is pretty confusing.

Seems the main problem is that the resource names are now concatenated from `.Release.Name` value which is set by parent chart (epinio) and not by the s3gw subchart itself.

I believe this "bug" can introduce more problems if used as a subchart in another project as well. Also there is a chance that the resource names will collide with names from the parent chart (which is not the case for epinio).

For epinio we would need a way how to set the s3gw resource names (esp. deployment, RS and secrets) independently on the parent chart name when used as a subchart and avoid using `.Release.Name` as only option. Seems that minio chart can handle this.

Some s3gw resource names used by epinio (doesn't use ingress nor s3gw ui):
```
|  Resource  |        0.14         |             0.18             |
|------------|---------------------|------------------------------|
| Deployment | s3gw                | epinio                       |
| ReplicaSet | s3gw-*              | epinio-*                     |
| Pod        | s3gw-*-*            | epinio-*-*                   |
| Secret     | s3gw-cluster-ip-tls | epinio-epinio-cluster-ip-tls |
| Secret     | s3gw-creds          | s3gw-creds                   |
| Service    | s3gw                | s3gw                         |
```

**Comment by giubacc** [comment]
Thanks for your reporting @thehejik .
The choice of s3gw, for its resources, to reason in terms of `.Release.Name` + `.Release.Namespace` has been made to allow the user to instantiate a virtually infinite number of instances of s3gw over a cluster.
This is very much tied with the fact that a single instance of s3gw, currently, handles a single volume.
This has been by design since the very beginning of the project.
I understand that when you are embedding the s3gw chart, this is not pleasant because the s3gw resources are someway named with the embedder names.
We can eventually revisit our naming composition to make that more s3gw explicit, maybe always adding an `s3gw` token to our resources.
@jecluis @m-ildefons

**Comment by giubacc** [comment]
@jhmarina @m-ildefons @jecluis 
The epino team has made the decision to not bump s3gw until the solution to add an `s3gw` token to all the s3gw related resource names.
If we agree on this solution, let's decide an implementation window for this.
