### ISSUE TITLE
rgw/sfs: Requesting bucket stats does not return any data

### ISSUE THREAD

**Issue by votdev** [s3gw-tech/s3gw#64]
Requesting stats of all available buckets via the AdminOps API should be possible via [http(s)://foo/admin/buckets?stats](https://docs.ceph.com/en/latest/radosgw/adminops/#get-bucket-info). This is done in Ceph Dashboard for example. But the s3gw only returns an empty list.

**Comment by votdev** [comment]
Connecting the s3gw-ui with a RGW of a SES7.1 cluster, the UI can query the users and buckets correctly. So i assume that something in our backend store does not work and the UI is doing the right thing.

![Bildschirmfoto vom 2022-08-16 17-37-14](https://user-images.githubusercontent.com/1897962/184921184-746f9666-8d79-4618-ba26-dd6c0583046c.png)

![Bildschirmfoto vom 2022-08-16 17-36-56](https://user-images.githubusercontent.com/1897962/184921217-912e0227-a074-44dc-a562-1f6ca1cbc8ab.png)

**Comment by votdev** [comment]
![Peek 2022-08-16 17-51](https://user-images.githubusercontent.com/1897962/184923894-39f097f3-7b55-4ef5-8285-c15312c7be48.gif)

**Comment by tserong** [comment]
I did a little digging, and AFAICT, `admin/bucket?stats` eventually ends up here in `RGWBucketAdminOp::info()`: https://github.com/aquarist-labs/ceph/blob/a36873c64013ec2684c645c409c5360fa01211cd/src/rgw/rgw_bucket.cc#L1267-L1287

That chunk of code tries to call `store->meta_list_keys_next()` to get a list of all the buckets, but, alas, it seems our current implementation of `SFStore::meta_list_keys_next()` doesn't know how to list buckets, all it knows how to do is list users (see https://github.com/aquarist-labs/ceph/blob/a36873c64013ec2684c645c409c5360fa01211cd/src/rgw/rgw_sal_sfs.cc#L256-L264). So that's probably returning a list of users, not buckets, which makes no sense in that context. That needs to be fixed to return a list of buckets when buckets are requested.  ~Once that's fixed, we also need to implement `SFStore::get_bucket()`, which currently just returns -ENOTSUP (see https://github.com/aquarist-labs/ceph/blob/a36873c64013ec2684c645c409c5360fa01211cd/src/rgw/store/sfs/sfs_bucket.cc#L29-L34)~. Scratch that, I think it's actually calling https://github.com/aquarist-labs/ceph/blob/a36873c64013ec2684c645c409c5360fa01211cd/src/rgw/store/sfs/sfs_bucket.cc#L53 which _is_ implemented. Anyway... I assume there might be other pieces missing too, but that's as far as I've gone so far.

**Comment by tserong** [comment]
I have a hideously disgusting hack that will fix this:

```diff --git a/src/rgw/rgw_sal_sfs.cc b/src/rgw/rgw_sal_sfs.cc
--- a/src/rgw/rgw_sal_sfs.cc
+++ b/src/rgw/rgw_sal_sfs.cc
@@ -46,6 +46,7 @@
 #include "store/sfs/writer.h"
 
 #include "rgw/store/sfs/sqlite/sqlite_users.h"
+#include "rgw/store/sfs/sqlite/sqlite_buckets.h"
 
 #define dout_subsys ceph_subsys_rgw
 
@@ -246,10 +247,18 @@ int SFStore::get_config_key_val(string name, bufferlist *bl) {
   return 0;
 }
 
+const char * const handle_bucket = "bucket";
+const char * const handle_user = "user";
+
 int SFStore::meta_list_keys_init(const DoutPrefixProvider *dpp,
                                          const string &section,
                                          const string &marker, void **phandle) {
   ldpp_dout(dpp, 10) << __func__ << ": TODO" << dendl;
+  if (section == "user") {
+    *phandle = (void *)handle_user;
+  } else if (section == "bucket") {
+    *phandle = (void *)handle_bucket;
+  }
   return 0;
 }
 
@@ -257,9 +266,15 @@ int SFStore::meta_list_keys_next(const DoutPrefixProvider *dpp,
                                          void *handle, int max,
                                          list<string> &keys, bool *truncated) {
   *truncated = false;
-  rgw::sal::sfs::sqlite::SQLiteUsers sqlite_users(db_conn);
-  auto ids = sqlite_users.get_user_ids();
-  std::copy(ids.begin(), ids.end(), std::back_inserter(keys));
+  if (handle == (void *)handle_user) {
+    rgw::sal::sfs::sqlite::SQLiteUsers sqlite_users(db_conn);
+    auto ids = sqlite_users.get_user_ids();
+    std::copy(ids.begin(), ids.end(), std::back_inserter(keys));
+  } else if (handle == (void *)handle_bucket) {
+    rgw::sal::sfs::sqlite::SQLiteBuckets sqlite_buckets(db_conn);
+    auto ids = sqlite_buckets.get_bucket_ids();
+    std::copy(ids.begin(), ids.end(), std::back_inserter(keys));
+  }
   return 0;
 }
 
```

@jecluis want me to stick that rotten thing in a PR? Bear in mind that I assume a real implementation of this would have  `meta_list_keys_init()` set `*phandle` to some instance of a class that knew how to list the relevant type of metadata, and then `meta_list_keys_next()` would call out to that class via `handle`. Looks like the RADOS SAL does something like that.

**Comment by tserong** [comment]
...actually, if `meta_list_keys_init()` set `*phandle` to a pointer to a new `rgw::sal::sfs::sqlite::SQLiteUsers` or an `rgw::sal::sfs::sqlite::SQLiteBuckets`, then `meta_list_keys_next()` called `get_user_ids()` or `get_bucket_ids()` on `handle`, that'd kinda move us in the right direction. Also we need to implement handling of `max` and `truncated`.

**Comment by jecluis** [comment]
@tserong PR would be great :) thanks
