### ISSUE TITLE
rgw/sfs: ResponseMetadata does not contain the props `RequestId` and `HostId`

### ISSUE THREAD

**Issue by votdev** [s3gw-tech/s3gw#646]
While testing the UI REST API i realized that the backend failed when calling [get_bucket_lifecycle_configuration](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/get_bucket_lifecycle_configuration.html). The error message was

```
pydantic.error_wrappers.ValidationError: 2 validation errors for GetBucketLifecycleConfigurationOutputTypeDef
response -> ResponseMetadata -> RequestId
  field required (type=value_error.missing)
response -> ResponseMetadata -> HostId
  field required (type=value_error.missing)
```

The type definition of the response model looks like:
```
GetBucketLifecycleConfigurationOutputTypeDef = TypedDict(
    "GetBucketLifecycleConfigurationOutputTypeDef",
    {
        "Rules": List[LifecycleRuleTypeDef],
        "ResponseMetadata": ResponseMetadataTypeDef,
    },
)

ResponseMetadataTypeDef = TypedDict(
    "ResponseMetadataTypeDef",
    {
        "RequestId": str,
        "HostId": str,
        "HTTPStatusCode": int,
        "HTTPHeaders": Dict[str, str],
        "RetryAttempts": int,
    },
)
```

The `ResponseMetadataTypeDef` specifies that ALL properties are expected in the response data to be parsed.

The response data looks like:

```
{
   "ResponseMetadata":{
      "HTTPStatusCode":200,
      "HTTPHeaders":{
         "content-type":"application/xml",
         "content-length":"267",
         "date":"Mon, 31 Jul 2023 15:42:01 GMT",
         "server":"Ceph Object Gateway (reef)",
         "connection":"Keep-Alive"
      },
      "RetryAttempts":0
   },
   "Rules":[
      {
         "Expiration":{
            "Days":365
         },
         "ID":"rule01",
         "Filter":{
            "Prefix":"dasda"
         },
         "Status":"Enabled"
      }
   ]
}
```

Based on the type definition i assume that `RequestId` and `HostId` are expected to be always returned by the S3 endpoint. This indicates that our s3gw returns only partial data of the expected `ResponseMetadata`.

References:
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/get-request-ids.html
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/get_bucket_lifecycle_configuration.html

**Comment by jecluis** [comment]
As far as I can tell, this is not a bug.

`HostId` and `RequestId` seem to only have to be present in case of error. In case of success, like the example above, it would not be expected to have `RequestId` (which is meant for support purposes, apparently), and I suspect neither would `HostId`. RGW itself conditions the existence of these only in case of an error.

As for boto's types, I think they are being a bit too eager. Keep in mind that `TypedDict` is not checked at runtime, and solely for type checkers. I believe this is why the error is not happening at boto's level but on our pydantic side -- because pydantic does validate at runtime.

We should keep in mind that those fields will be available in case there's an error, and won't be present otherwise.

@votdev is this satisfactory?

**Comment by votdev** [comment]
> @votdev is this satisfactory?

I'm fine with that. I'll simply define a new response type with `total=False`, so Pydantic will be happy.
