### ISSUE TITLE
[BUG] UI: not able to see/modify retention modes / legal holds for versions 

### ISSUE THREAD

**Issue by giubacc** [s3gw-tech/s3gw#745]
**Describe the bug** A clear and concise description of what the bug is.

User cannot see/modify rentention modes / legal holds for object versions; this information is available only for the latest version of the object.

**Comment by jecluis** [comment]
@votdev any idea if this comes from sfs or whether this is just a UI issue?

**Comment by giubacc** [comment]
My idea is that the UI, for **every** version of the object, should call the [GetObjectRetention](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectRetention.html) and the [GetObjectLegalHold](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectLegalHold.html) APIs.
This item is more a missing feature rather than a bug (it depends how you want to see it ;) )

**Comment by jecluis** [comment]
Gotcha. @votdev I'm leaning towards a feature request, what do you think?

**Comment by votdev** [comment]
> User cannot see/modify rentention modes / legal holds for object versions; this information is available only for the latest version of the object.

> My idea is that the UI, for **every** version of the object, should call the [GetObjectRetention](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectRetention.html) and the [GetObjectLegalHold](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectLegalHold.html) APIs. This item is more a missing feature rather than a bug (it depends how you want to see it ;) )

This raises some questions:
- Why is this needed. What is the use case/scenario for this?
- Where should this info be displayed? In the object version history page?

I can not imagine a user scenario where it is necessary to see and change the retention mode and legal hold of an object version that is NOT the latest version (which in my understanding are archived versions).

In my understanding object versions that do not have the label "Latest" are archived versions that are only used for recovery. If such an archived version has been restored, then the user can make changes to the legal hold and retention settings. Before that, it just doesn't make sense since they are ONLY archived objects.

If a user is really in the need to change these settings for "archived" versions, they can still use the S3 CLI.

> I'm leaning towards a feature request, what do you think?

I do not see any sense in supporting this in the UI.

**Comment by giubacc** [comment]
What follows reflect my thinking about this and should be taken just as a reasoning without claiming to be the correct way of interpreting things.

In our world there is S3 that offers a set of APIs that permit to do something over versioned objects.
Over this (S3) technical layer we build on the UI an "opinionated vision" that implements an arbitrary model.
Deciding what this model should suggest to the user and how the versioned objects should be interpreted is something we have decided as software engineers based on what made us more sense.
I'm not here saying one choice should be better than another.
I'm saying that for an user could be beneficial to be able to see and modify retention modes and legal hold for all the versions of an object.
Saying that the latest version is "special" and all the other versions are just "archived versions" is an arbitrary vision.
An user could legitimately argue on this because he/she uses S3 in another way. 
From an S3 point of view, there is no difference between versions, every version has the same dignity.
Let's keep in mind that we don't know how an user could want to use S3; what makes no sense for us, could for an user.

**Comment by votdev** [comment]
As discussed with @jecluis today, we will not implement this feature until a user explicitly expresses this wish.

What is technically feasible does not necessarily have to be implemented in a UI, otherwise unfortunately the UX will suffer. There will always be edge cases that cannot be represented in a product intended for the general public. Otherwise, you'll end up with a UI that has a gruesome UX.

> Let's keep in mind that we don't know how an user could want to use S3; what makes no sense for us, could for an user. 

It is clear that we cannot implement all the requirements and scenarios of the users. But we as the developers of the project should define a UX that is consistently reflected in the UI and should fit 99% of the users requirements.

The fact is that the S3 API calls consider the latest version as default, since a version specification in the API is only optional. And this is how I think the view on the objects is seen by the vast majority of users. The "latest" or "current" version is the version that is worked with, all others are considered archived or backup.

For users with special workflow which does not fit with our UI and UX there is still the possibility to use the CLI.

**Comment by jecluis** [comment]
In addition, there is another thing to consider, as far as I understand: user capabilities that allow or disallow removing said versions under retention.

Currently we don't have information on the UI on which users have the capabilities to perform such operations. We would have to rely on making a blind call to s3gw and wait for a permission denied or a success. This may lead to confusion and it's generally a bad UX.

As such, we're making the executive call not to support this at this time. As @votdev said, this may be revisited if / when the need arises.

**Comment by jecluis** [comment]
Closing as not planned.

**Comment by giubacc** [comment]
> In addition, there is another thing to consider, as far as I understand: user capabilities that allow or disallow removing said versions under retention.
> 
> Currently we don't have information on the UI on which users have the capabilities to perform such operations. We would have to rely on making a blind call to s3gw and wait for a permission denied or a success. This may lead to confusion and it's generally a bad UX.

Be warned that this also applies to the latest version.
This to say that if we support changing  rentention modes / legal holds for the latest version we could fall into this problem as well.
If we decided not to support change  rm / lh by the UI we are good!
