### ISSUE TITLE
rgw/sfs: store newly added fields to buckets in sqlite

### ISSUE THREAD

**Issue by 0xavi0** [s3gw-tech/s3gw#85]
After merging https://github.com/aquarist-labs/ceph/pull/27 we'd need to store the newly added fields in bucket to sqlite and also load their values when retrieving a bucket's info.

Fields to store:
* zonegroup_id
* bucket_version
* bucker_version_tag
* quota

Also confirm if we need the `swift` related fields. I guess we don't need them now.

This is to make consistent queries of the information that the UI, for example, gets when creating a bucket and the information that it gets when the bucket was already created.

Those fields will be returned when creating the bucket but not when loading an existing bucket which could drive to inconsistencies.

**Comment by giubacc** [comment]
other fields to store:

- ~~swift_ver_location~~
- ~~swift_versioning~~
- ~~attrs~~

~~`attrs` seems something used in dbstore but not really used, because `RGWBucketInfo` does not contain such information, we are skipping this.~~

ERRATA: `attrs` seems used when dealing with ACLs; but this field is handled in some special way.
better investigate this on a dedicate issue, probably [this](https://github.com/aquarist-labs/s3gw/issues/86) is a good candidate.

UPDATE: no need to store swift fields, we don't support `swift`.

**Comment by giubacc** [comment]
just for posterity: for the time being, we decided not to proceed adding:

- bucket_version
- bucker_version_tag
